[workspace]
members = [".", "runner", "lsp"]

[package]
name = "zed_http"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"


[lib]
path = "src/http.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.6.0"

[profile.release]
lto = true
opt-level = "z"
