id = "zhttp"
name = "zhttp"
description = "HTTP file syntax highlighting and request execution"
version = "0.1.0"
schema_version = 1
authors = ["st.ilya.101@gmail.com"]
repository = "https://github.com/stillya/zhttp"


[language_servers.zhttp-lsp]
name = "zhttp-lsp"
languages = ["http"]

[grammars.http]
repository = "https://github.com/rest-nvim/tree-sitter-http"
commit = "e061995f0caf2fa30f68fa1fdf2c08bcbd4629a8"
