[package]
name = "zhttp"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "zhttp"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
ureq = "2"
serde_json = "1"
